package io.savor.common.exceptions.status;